all:
    hosts:
        localhost: localhost
    vars:
        ansible_user: 
        ansible_connection: winrm
        ansible_port: 5985
        ansible_winrm_transport: credssp
        ansible_password: 